from django.contrib import admin
from customers.models import *

admin.site.register(Religion)
admin.site.register(Address)
admin.site.register(Users)
admin.site.register(Vendors)
admin.site.register(Vendor_Cordinators)
admin.site.register(Venue_Types)
admin.site.register(Card_Types)
admin.site.register(Beautician_Types)
admin.site.register(Music_Types)
admin.site.register(Gift_Types)
admin.site.register(Photo_Types)
admin.site.register(Video_Types)
admin.site.register(Bakery_Types)
admin.site.register(Ghodi_Bagghi_Types)
admin.site.register(Band_Types)
admin.site.register(Mehendi_Types)
admin.site.register(Fireworks_Types)
admin.site.register(Tent_Types)
admin.site.register(Videos)
admin.site.register(Venues)
admin.site.register(Cards)
admin.site.register(Cart)
admin.site.register(Product_Pictures)
admin.site.register(Orders)
admin.site.register(Delivery_Status)
admin.site.register(Wishlist)
admin.site.register(Reviews)
